DROP TABLE users
IF EXISTS;
DROP TABLE dishes
IF EXISTS;
DROP TABLE menus
IF EXISTS;
DROP TABLE restaurants
IF EXISTS;
DROP SEQUENCE global_seq
IF EXISTS;

CREATE SEQUENCE global_seq
  AS INTEGER
    START WITH 100000;

CREATE TABLE users (
  id         INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name       VARCHAR(50) NOT NULL,
  email      VARCHAR(50) NOT NULL,
  password   VARCHAR(16) NOT NULL,
  registered TIMESTAMP DEFAULT now(),
  enabled    BOOLEAN   DEFAULT TRUE,
  role       VARCHAR(5)  NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON users (email);

CREATE TABLE restaurants (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name          VARCHAR(50) NOT NULL,
  address       VARCHAR(50) NOT NULL,
  time_to_up    TIME DEFAULT '09:00:00',
  time_to_close TIME DEFAULT '23:00:00'
);

CREATE TABLE menus (
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  registered    TIMESTAMP DEFAULT now(),
  restaurant_id INTEGER NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurants (id)
    ON DELETE CASCADE
);

CREATE TABLE dishes (
  id      INTEGER GENERATED BY DEFAULT AS SEQUENCE global_seq PRIMARY KEY,
  name    VARCHAR(50) NOT NULL,
  price   INTEGER     NOT NULL,
  menu_id INTEGER     NOT NULL,
  FOREIGN KEY (menu_id) REFERENCES menus (id)
    ON DELETE CASCADE
);
